### ISSUE TITLE
Rails new with webpack

### ISSUE THREAD

**Issue by Jonrw97** [dewaldreynecke/rails-templates#1]
Not entirely sure how but webpack and hotwired are not added in the package.json, so yarn can't install them thus rails can't find webpacker when you run dev(or rails s & yarn build --watch)
I can't see how they add it in le wagon templates, but easy fix is just adding the dependencies after running rails new  
### dev
<img width="868" alt="Screenshot 2023-07-26 175841" src="https://github.com/dewaldreynecke/rails-templates/assets/91339335/aa3405bb-2528-4f5d-8cb3-d321f04540cc">

### rails s
<img width="947" alt="Screenshot 2023-07-26 175925" src="https://github.com/dewaldreynecke/rails-templates/assets/91339335/83b73f0d-f2c4-4dc0-81c5-ba3fe9e6da8a">

**Comment by dewaldreynecke** [comment]
Hi @Jonrw97 

It works for me when using this (from the README):
```
rails new \
  -d postgresql \
  -j webpack \
  -m https://raw.githubusercontent.com/dewaldreynecke/rails-templates/main/auth.rb \
  CHANGE_THIS_TO_YOUR_RAILS_APP_NAME
```

Notice the `-j webpack` which is what does the trick.

Will you please test again and confirm?

**Comment by Jonrw97** [comment]
Hey @dewaldreynecke 

Yes I had assumed the `-j webpack` was responsible to sort it out, wasn't sure since I haven't messed with templates before.

I have tested again, still happens but it seems to be something with my nvm that has bugged out recently because le wagon templates now have the same issue, sorry for the mix up.

Thanks
